### ISSUE TITLE
Show start or play when ambientnoise not playing?

### ISSUE THREAD

**Issue by roachsinai** [m-pilia/plasma-applet-ambientnoise#11]
![image](https://user-images.githubusercontent.com/9500049/52908768-3ae4fc00-32b7-11e9-8e2f-b18b0604ae36.png)

Seems always show `Pause` now.

**Comment by roachsinai** [comment]
Press right mouse button on ambientnoise icon will show the above image.

**Comment by m-pilia** [comment]
Hi! Good catch, thanks! Should be fixed in the [fix-playpause branch](/m-pilia/plasma-applet-ambientnoise/tree/fix-playpause).

**Comment by roachsinai** [comment]
So, mainly these two line https://github.com/m-pilia/plasma-applet-ambientnoise/blob/12f2787f76dfe41ca4812b7ce727ec2af5d6ef9a/plasmoid/contents/js/scripts.js#L134 changes the text which I focus? I'm new to qml and qt. And know more thing at [Context menu](https://techbase.kde.org/Development/Tutorials/Plasma4/JavaScript/API-PlasmoidObject#Context_menu) follow your code. 

Thanks for your work. Will test it.

**Comment by roachsinai** [comment]
Worked!

**Comment by m-pilia** [comment]
>So, mainly these two line

Yes, those lines replace a "play" action with "pause" in the context menu, and vice versa. Not an elegant solution, it would be better if it was possible to use [property binding](https://doc.qt.io/qt-5/qtqml-syntax-propertybinding.html) but afaik it should not be possible for the arguments of `addAction()`.

>Worked!

Great, thanks for reporting this!
