### ISSUE TITLE
"QtQuick.Controls" version 2.2 is not installed

### ISSUE THREAD

**Issue by dennisotugo** [m-pilia/plasma-applet-ambientnoise#2]
`Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.ambientnoise/contents/ui/main.qml:21:1: module "QtQuick.Controls" version 2.2 is not installed
`
It cannot run on fedora 26 because it demands qtquick2.2 that requires qt5.9 that is not currently available in fedora repo. Any side hack to get it to run on qt5.7

**Comment by m-pilia** [comment]
Hello!
Actually I think it should be possible to adapt the plasmoid to use Qt 5.7 without rewriting everything, by using the ScrollView from QtQuick.Controls 1.4. You can try the version in [this branch](https://github.com/m-pilia/plasma-applet-ambientnoise/tree/qt5.7), that uses a version of the components [compatible with Qt 5.7](https://doc.qt.io/qt-5/qtquickcontrols2-index.html). However, there should be some (hopefully minor) differences in the appearance (that is why I used QtQuick Controls 2 in principle). I am sorry I could not test this hack on a real Qt 5.7 installation, right now I have only Qt 5.9 on my machines...

**Comment by dennisotugo** [comment]
Works like a charm. Thanks
