### ISSUE TITLE
Issues with the icon

### ISSUE THREAD

**Issue by dennisotugo** [m-pilia/plasma-applet-ambientnoise#3]
The icon on plasma does not display, change install location to hicolor because that seems to fix the issue

**Comment by m-pilia** [comment]
Hello again and thanks for the feedback!
I think it depends on the theme management, since the current icon should belong to the breeze theme. I will also add an hicolor icon for better compatibility with other themes.

**Comment by dennisotugo** [comment]
@m-pilia Even when using breeze default theme, it still doesn't show. Also any plans for support for dark themes?

**Comment by m-pilia** [comment]
You are right, I think the icon installation is messed up. I tried another method (and I added a dark version of the icon), I hope now it works. I'm only sorry for the poor artistic quality, I am very terrible at drawing...

**Comment by dennisotugo** [comment]
Sorry I left this open for too long. It works now, the art of the icon is ok
