### ISSUE TITLE
Packaging of Sound

### ISSUE THREAD

**Issue by dennisotugo** [m-pilia/plasma-applet-ambientnoise#6]
Any probability of packaging the widgets with sounds that play on a continuous loop

**Comment by m-pilia** [comment]
Hello! I am not sure I get the question correctly: is it about providing some default sounds with the widget, or do you have a problem with the sounds not playing in a infinite loop in your installation?

For the second case, they should already play as infinite loop, and if they do not then it is definitely a bug! (I do not see how it can be related to the QML code, but it may be a quirk in the audio backend)

For the first case, I did not bundle default sounds mostly for two reasons. The first is that a set of basic sounds and related icons is already available with [anoise](http://anoise.tuxfamily.org/), that is easy to install as a package in the main distros, like [K]Ubuntu (via some PPAs) or Arch (through the AUR), so just installing the anoise package should give sounds and icons ready (at most after fixing the path in the widget's settings). In fact I designed this plugin to be naturally compatible with anoise. The other reason is that I preferred to not have license and copyright complications by including audio files produced by others, even if released under a free license. I am actually considering to produce some audio files myself, but in this period I do not have my Zoom recorder at hand. I hope to be able to do that in the future, however.

**Comment by dennisotugo** [comment]
I meant about providing packaged sound, anoise is not easy to install when not in arch or ubuntu and the size is just too big. You could try soundbible, they have free sound, high quality and low size with proper licensing. Also the loop does work well.

**Comment by dennisotugo** [comment]
I could provide links to soundbible sounds such as rain, thunder etc. 6 sounds in total. it will not increase the plasmoid size beyond 4mb
