### ISSUE TITLE
Delete icon not show.

### ISSUE THREAD

**Issue by roachsinai** [m-pilia/plasma-applet-ambientnoise#7]
![image](https://user-images.githubusercontent.com/9500049/52765671-c19f9c00-305f-11e9-877e-715b12fbddfc.png)

So, could you please tell me there the delete icon stored? And then I can check whether it exists on my laptop.

**Comment by m-pilia** [comment]
Hi @roachsinai! The icons are fetched from the system theme, the one that is not showing up is the "delete" icon. I just checked and that icon is provided by breeze but not by hicolor, which is bad. I just tried to fix this, you can try the version in [fix-delete-icon branch](/m-pilia/plasma-applet-ambientnoise/tree/fix-delete-icon), let me know if it solves your problem!

**Comment by roachsinai** [comment]
Yes, `edit-delete` fixed this, shows:

![image](https://user-images.githubusercontent.com/9500049/52828842-6c1dca80-3105-11e9-8d47-57e7a9e2976c.png)

**Comment by m-pilia** [comment]
Perfect, thank you for reporting this!
