### ISSUE TITLE
Overwriting and soft code

### ISSUE THREAD

**Issue by gusbemacbe** [m-pilia/plasma-applet-ambientnoise#8]
Hello @m-pilia !

If I add the icons to the icons set, will they overwrite the original icons of your plasmoid applet? Are they hardcoded or softcoded?

**Comment by m-pilia** [comment]
Hi @gusbemacbe!
All icons are fetched from the system theme, so if your theme provides icons with the right name, they should be picked up and used by the plasmoid. All icons are standard from KDE themes, except for the one called ["ambientnoise"](/m-pilia/plasma-applet-ambientnoise/tree/master/icons), that I created myself.

So, for instance, if you want to change the main icon of the plasmoid, you should add a custom icon called "ambientnoise" to your icon theme.

**Comment by gusbemacbe** [comment]
See, @roachsinai, I will add in the next version, I am focusing on adding Suru++ support for gradient in the small icons.

**Comment by roachsinai** [comment]
Yes, thanks for all you guys' work!
