### ISSUE TITLE
Resotre session after reboot or shutdown.

### ISSUE THREAD

**Issue by roachsinai** [m-pilia/plasma-applet-ambientnoise#9]
Seem I have to replay the ambientnoise each time after reboot, right? If so, is there a way to resotre it auto?

**Comment by m-pilia** [comment]
Hi @roachsinai! Thanks for reporting this issue. I can implement the possibility to keep the player status across shutdowns/reboots. I will probably implement this over the weekend!

**Comment by m-pilia** [comment]
Hi @roachsinai!
I implemented the persistent state across reboots/shutdowns for the plasmoid, you can find the new version in the [keep-state branch](/m-pilia/plasma-applet-ambientnoise/tree/keep-state). Please let me know if it works for you!

**Comment by roachsinai** [comment]
It's great! Thanks!
